name: Build and Test HTML/CSS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install -g stylelint@14.0.0 stylelint-config-standard@24.0.0 htmlhint prettier

      - name: Format HTML
        run: prettier --write ./*.html

      - name: Run HTML linting with custom config
        run: htmlhint --config .htmlhintrc ./*.html

      - name: Run CSS linting
        run: stylelint "**/*.css"
