name: Build and Test HTML/CSS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (optional for linting and minification)
        uses: actions/setup-node@v3
        with:
          node-version: '16' # No es obligatorio, pero si vas a usar herramientas como linters o minificadores

      - name: Install dependencies
        run: npm install -g stylelint htmlhint prettier stylelint-config-standard

      - name: Run HTML linting
        run: htmlhint ./*.html # Valida los archivos HTML

      - name: Run CSS linting
        run: stylelint "**/*.css" # Valida los archivos CSS

      - name: Minify CSS
        run: |
          npm install -g clean-css-cli # Instala el minificador de CSS
          cleancss -o ./dist/styles.min.css ./styles.css # Minifica el archivo CSS

      - name: Build Project (if necessary)
        run: |
          mkdir -p ./dist
          cp -r ./index.html ./styles.css ./dist/ # Copia los archivos a la carpeta de distribución (opcional)

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: html-css-build
          path: ./dist
