name: Build and Test HTML/CSS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (for linting and minification)
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Usamos la versión 18 para evitar problemas de compatibilidad

      - name: Install dependencies
        run: |
          npm install -g stylelint stylelint-config-standard postcss postcss-cli htmlhint prettier clean-css-cli

      - name: Configure Stylelint
        run: |
          echo '{
            "extends": "stylelint-config-standard",
            "rules": {
              "at-rule-no-unknown": [true, {
                "ignoreAtRules": ["keyframes", "mixin", "include"]
              }]
            }
          }' > .stylelintrc.json

      - name: Run HTML linting
        run: htmlhint "**/*.html" # Valida todos los archivos HTML en el proyecto

      - name: Run CSS linting
        run: stylelint "**/*.css" # Valida todos los archivos CSS en el proyecto

      - name: Minify CSS
        run: |
          mkdir -p ./dist
          cleancss -o ./dist/styles.min.css ./styles.css # Minifica y guarda el CSS en la carpeta de distribución

      - name: Build Project (copy files to dist)
        run: |
          cp -r ./index.html ./dist/ # Copia el archivo HTML a la carpeta de distribución

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: html-css-build
          path: ./dist # Carga la carpeta dist como un artefacto del build
